/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projetoindividual2;

import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Aluno
 */
public class Barras2 extends javax.swing.JFrame {

    // criando variaveis globais para guardar as informações
   Integer cliques = 0;
   
   Double mediaCpu = 0.0;
   Double minimoCpu = 0.0;
   Double maximaCpu = 0.0;
   
   Double mediaDisco = 0.0;
   Double minimoDisco = 0.0;
   Double maximaDisco = 0.0;
   
   Double mediaMemoria = 0.0;
   Double minimoMemoria = 0.0;
   Double maximaMemoria= 0.0;
   
   
   
  
           
    public Barras2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prgBar1 = new javax.swing.JProgressBar();
        prgBar2 = new javax.swing.JProgressBar();
        prgBar3 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCpu = new javax.swing.JLabel();
        lblDisco = new javax.swing.JLabel();
        lblMemoria = new javax.swing.JLabel();
        btnacao = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblMediaCpu = new javax.swing.JLabel();
        lblMinimoCpu = new javax.swing.JLabel();
        lblMaximoCpu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblMediaDisco = new javax.swing.JLabel();
        lblMinimoDisco = new javax.swing.JLabel();
        lblMaximoDisco = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblMediaMemoria = new javax.swing.JLabel();
        lblMinimoMemoria = new javax.swing.JLabel();
        lblMaximoMemoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPU");

        jLabel2.setText("DISCO");

        jLabel3.setText("MEMÓRIA");

        lblCpu.setText("jLabel4");

        lblDisco.setText("jLabel5");

        lblMemoria.setText("jLabel6");

        btnacao.setText("Fazer leitura de dados");
        btnacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacaoActionPerformed(evt);
            }
        });

        jLabel4.setText("CPU");

        lblMediaCpu.setText("Média:");

        lblMinimoCpu.setText("Minima:");

        lblMaximoCpu.setText("Máxima:");

        jLabel8.setText("DISCO");

        lblMediaDisco.setText("Média:");

        lblMinimoDisco.setText("Minima:");

        lblMaximoDisco.setText("Máxima:");

        jLabel12.setText("MEMÓRIA");

        lblMediaMemoria.setText("Média:");

        lblMinimoMemoria.setText("Minima:");

        lblMaximoMemoria.setText("Máxima:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prgBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblCpu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(prgBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(prgBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnacao, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(lblMediaDisco)
                                .addGap(0, 18, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblMinimoCpu)
                                        .addComponent(lblMaximoCpu)
                                        .addComponent(lblMediaCpu)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMaximoMemoria)
                                            .addComponent(lblMinimoMemoria)
                                            .addComponent(lblMediaMemoria))
                                        .addGap(3, 3, 3))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaximoDisco)
                            .addComponent(lblMinimoDisco))
                        .addGap(7, 7, 7)))
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCpu)
                    .addComponent(lblMediaCpu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prgBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblDisco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMinimoCpu)
                        .addGap(19, 19, 19)))
                .addComponent(prgBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblMaximoCpu)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblMemoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prgBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnacao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(lblMediaDisco)))
                .addGap(35, 35, 35)
                .addComponent(lblMinimoDisco)
                .addGap(30, 30, 30)
                .addComponent(lblMaximoDisco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMediaMemoria)
                .addGap(19, 19, 19)
                .addComponent(lblMinimoMemoria)
                .addGap(18, 18, 18)
                .addComponent(lblMaximoMemoria)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    private void btnacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacaoActionPerformed
       
        prgBar1.setMinimum(0);
        prgBar1.setMaximum(2400);
        
        prgBar2.setMinimum(0);
        prgBar2.setMaximum(186000);
        
        prgBar3.setMinimum(0);
        prgBar3.setMaximum(8000);
        
        Integer progresCpu = ThreadLocalRandom.current().nextInt(0,2400);
        
        Integer progresDisco = ThreadLocalRandom.current().nextInt(0,186000);
        
        Integer progresMemoria = ThreadLocalRandom.current().nextInt(0,8000);
        
        prgBar1.setValue(progresCpu);
        
        prgBar2.setValue(progresDisco);
        
        prgBar3.setValue(progresMemoria);
        
        //Convertendo para double
        
        Double dProgresCpu = Double.valueOf(progresCpu);
        Double dProgresDisco = Double.valueOf(progresDisco);
        Double dprogresMemoria = Double.valueOf(progresMemoria);
        
        
        Double infoCpu = dProgresCpu / 1000;
        Double infoDisco = dProgresDisco / 1000;
        Double infoMemoria = dprogresMemoria /1000;
       
        
        
        
       //printando os resultados da cpu
        
       String resultado1 = String.format("%.2fGhz ",infoCpu);
       
        lblCpu.setText(resultado1);
        
        System.out.println(progresCpu);
        System.out.println(infoCpu);
        
        //pintando os resultados do disco 
        
        String resultado2 = String.format("%.2fGB",infoDisco);
        
        lblDisco.setText(resultado2);
        
        System.out.println(progresDisco);
        System.out.println(infoDisco);
        
        //printando os resultados da memoria
        
        String resultado3 = String.format("%.2fGB",infoMemoria);
        
        lblMemoria.setText(resultado3);
        
        System.out.println(progresMemoria);
        System.out.println(infoMemoria);
        
        //somar os numeros criados a cada clique no botao
        cliques++;
        
        // Formulando as medias
        
        mediaCpu=mediaCpu+infoCpu;
        Double mediacpu2 = mediaCpu/cliques;
        
        mediaDisco=mediaDisco+infoDisco;
        Double mediadisco2 =mediaDisco/cliques;
        
        mediaMemoria=mediaMemoria+infoMemoria;
        Double mediamemoria2 = mediaMemoria/cliques;
        
        //Printando os valores da media
         
        lblMediaCpu.setText("Média:"+String.format("%.2fGhz",mediacpu2));
        lblMediaDisco.setText("Média:"+String.format("%.2fGB",mediadisco2 ));
        lblMediaMemoria.setText("Média:"+String.format("%.2fGB",mediamemoria2 ));
               
        // criando o minimo e o maximo utilizando if 
        //cpu
        if (infoCpu > maximaCpu){
            maximaCpu = infoCpu;
            lblMaximoCpu.setText("Maxima:"+String.format("%.2fGhz", maximaCpu));
        }
        if (infoCpu<minimoCpu || minimoCpu ==0) {
            minimoCpu = infoCpu;
            lblMinimoCpu.setText("Minima:"+String.format("%.2fGhz", minimoCpu));
        }
        
        //Disco
        
        if (infoDisco > maximaDisco){
            maximaDisco = infoDisco;
            lblMaximoDisco.setText("Maxima:"+String.format("%.2fGB", maximaDisco));
        }
        if (infoDisco<minimoDisco || minimoDisco ==0) {
            minimoDisco = infoDisco;
            lblMinimoDisco.setText("Minima:"+String.format("%.2fGB", minimoDisco));
        }
        
        //memoria
        
        if (infoMemoria > maximaMemoria){
            maximaMemoria = infoMemoria;
            lblMaximoMemoria.setText("Maxima:"+String.format("%.2fGB", maximaMemoria));
        }
        if (infoMemoria<minimoMemoria || minimoMemoria ==0) {
            minimoMemoria = infoMemoria;
            lblMinimoMemoria.setText("Minima:"+String.format("%.2fGB", minimoMemoria));
        }
    }//GEN-LAST:event_btnacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barras2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barras2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barras2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barras2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barras2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblCpu;
    private javax.swing.JLabel lblDisco;
    private javax.swing.JLabel lblMaximoCpu;
    private javax.swing.JLabel lblMaximoDisco;
    private javax.swing.JLabel lblMaximoMemoria;
    private javax.swing.JLabel lblMediaCpu;
    private javax.swing.JLabel lblMediaDisco;
    private javax.swing.JLabel lblMediaMemoria;
    private javax.swing.JLabel lblMemoria;
    private javax.swing.JLabel lblMinimoCpu;
    private javax.swing.JLabel lblMinimoDisco;
    private javax.swing.JLabel lblMinimoMemoria;
    private javax.swing.JProgressBar prgBar1;
    private javax.swing.JProgressBar prgBar2;
    private javax.swing.JProgressBar prgBar3;
    // End of variables declaration//GEN-END:variables
}
